-- Initial schema for the Bear Lake cabin app.
--
-- Conventions, applied uniformly:
--   * CHAR(36) primary keys holding UUIDs generated by the application
--   * DATETIME(3) columns, always UTC, always written by the application —
--     no DEFAULT CURRENT_TIMESTAMP and no ON UPDATE. Article concurrency
--     control compares updated_at exactly, so the application must own it.
--   * utf8mb4 with a case-insensitive collation, which is what makes the
--     unique index on users.email case-insensitive at the database level.
--   * Users are deactivated, never deleted, so their authored rows survive.

CREATE TABLE users (
  id                   CHAR(36)              NOT NULL,
  display_name         VARCHAR(100)          NOT NULL,
  email                VARCHAR(255)          NOT NULL,
  password_hash        VARCHAR(255)          NOT NULL,
  role                 ENUM('admin','member') NOT NULL,
  must_change_password TINYINT(1)            NOT NULL,
  is_active            TINYINT(1)            NOT NULL,
  last_login_at        DATETIME(3)           NULL,
  created_at           DATETIME(3)           NOT NULL,
  updated_at           DATETIME(3)           NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Persisted so sessions can be revoked on password change, admin reset, and
-- deactivation. Only the hash is stored; the token itself is never at rest.
CREATE TABLE refresh_tokens (
  id         CHAR(36)    NOT NULL,
  user_id    CHAR(36)    NOT NULL,
  token_hash CHAR(64)    NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  revoked_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_refresh_tokens_token_hash (token_hash),
  KEY ix_refresh_tokens_user_id (user_id),
  CONSTRAINT fk_refresh_tokens_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- starts_at/ends_at are UTC instants for timed events and midnight-anchored
-- calendar dates for all-day events, distinguished by is_all_day.
CREATE TABLE events (
  id         CHAR(36)     NOT NULL,
  title      VARCHAR(200) NOT NULL,
  notes      TEXT         NULL,
  starts_at  DATETIME(3)  NOT NULL,
  ends_at    DATETIME(3)  NOT NULL,
  is_all_day TINYINT(1)   NOT NULL,
  created_by CHAR(36)     NOT NULL,
  created_at DATETIME(3)  NOT NULL,
  updated_at DATETIME(3)  NOT NULL,
  PRIMARY KEY (id),
  KEY ix_events_starts_at (starts_at),
  KEY ix_events_ends_at (ends_at),
  CONSTRAINT fk_events_created_by
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- The index matches the keyset pagination order: (posted_at DESC, id DESC).
CREATE TABLE announcements (
  id         CHAR(36)    NOT NULL,
  body       TEXT        NOT NULL,
  posted_at  DATETIME(3) NOT NULL,
  created_by CHAR(36)    NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY ix_announcements_posted_at_id (posted_at, id),
  CONSTRAINT fk_announcements_created_by
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE quick_tips (
  id         CHAR(36)    NOT NULL,
  body       TEXT        NOT NULL,
  sort_order INT         NOT NULL,
  created_by CHAR(36)    NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY ix_quick_tips_sort_order (sort_order),
  CONSTRAINT fk_quick_tips_created_by
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE info_categories (
  id         CHAR(36)     NOT NULL,
  title      VARCHAR(100) NOT NULL,
  sort_order INT          NOT NULL,
  created_at DATETIME(3)  NOT NULL,
  updated_at DATETIME(3)  NOT NULL,
  PRIMARY KEY (id),
  KEY ix_info_categories_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ON DELETE RESTRICT enforces plan D2 at the database level as well as in the
-- service: deleting a category that still holds articles is refused, because
-- cascading away written content is unrecoverable.
CREATE TABLE info_articles (
  id             CHAR(36)                   NOT NULL,
  category_id    CHAR(36)                   NOT NULL,
  title          VARCHAR(200)               NOT NULL,
  blocks         JSON                       NOT NULL,
  schema_version INT                        NOT NULL,
  status         ENUM('draft','published')  NOT NULL,
  sort_order     INT                        NOT NULL,
  created_by     CHAR(36)                   NOT NULL,
  created_at     DATETIME(3)                NOT NULL,
  updated_at     DATETIME(3)                NOT NULL,
  PRIMARY KEY (id),
  KEY ix_info_articles_category_sort (category_id, sort_order),
  CONSTRAINT fk_info_articles_category
    FOREIGN KEY (category_id) REFERENCES info_categories (id) ON DELETE RESTRICT,
  CONSTRAINT fk_info_articles_created_by
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
